### ISSUE TITLE
[Bug]: Can't pass `read_only` to the Python wrapper's repository creation API

### ISSUE THREAD

**Issue by yonipeleg33** [treeverse/lakeFS#7848] opened 2024-06-10 10:57 UTC
### What happened?

The Python wrapper is not familiar with the `read_only` optional argument that can be passed to the `createRepository` API (this is the operation id in `swagger.yml`).

Steps to Reproduce:
1. Write a Python file:
```python
import lakefs
from lakefs.client import Client

clt = Client(
    username="<username>",
    password="<password>",
    host="<host>",
)
repo = lakefs.Repository(repository_id="<repo id>", client=clt).create(
    storage_namespace="<namespace>",
    read_only=True,
)
```
2. Run it: `python <filename>.py`
3. Expect the following result:
```
...
    raise ApiTypeError(
lakefs_sdk.exceptions.ApiTypeError: Got an unexpected keyword argument 'read_only' to method create_repository

```

### Expected behavior

This should work.
For example, the following equivalent code works using the Rust client:
```rust
#[tokio::main]
async fn main() -> anyhow::Result<()> {
    let config = Configuration {
        base_path: "<url>".to_string(),
        basic_auth: Some((
            "<user>".to_string(),
            Some("<password>".to_string()),
        )),
        ..Configuration::default()
    };

    lakefs_sdk::apis::repositories_api::create_repository(
        &config,
        RepositoryCreation {
            name: "<repo>".to_string(),
            storage_namespace: "<namespace>"
                .to_string(),
            read_only: Some(true),
            ..RepositoryCreation::default()
        },
        None,
    )
    .await
    .context("creating repo")?;
    Ok(())
}
```

### Relevant log output

```shell
Here's the full error produced by the Python code:

  File "/home/<user>/workspace/playground/lakefs-rs-pg/../pg.py", line 9, in <module>
    repo = lakefs.Repository(repository_id="<repo>", client=clt).create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/<user>/workspace/playground/venv/lib/python3.11/site-packages/lakefs/repository.py", line 65, in create
    repo = self._client.sdk_client.repositories_api.create_repository(repository_creation, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/<user>/workspace/playground/venv/lib/python3.11/site-packages/pydantic/v1/decorator.py", line 40, in wrapper_function
    return vd.call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/<user>/workspace/playground/venv/lib/python3.11/site-packages/pydantic/v1/decorator.py", line 134, in call
    return self.execute(m)
           ^^^^^^^^^^^^^^^
  File "/home/<user>/workspace/playground/venv/lib/python3.11/site-packages/pydantic/v1/decorator.py", line 206, in execute
    return self.raw_function(**d, **var_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/<user>/workspace/playground/venv/lib/python3.11/site-packages/lakefs_sdk/api/repositories_api.py", line 91, in create_repository
    return self.create_repository_with_http_info(repository_creation, bare, **kwargs)  # noqa: E501
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/<user>/workspace/playground/venv/lib/python3.11/site-packages/pydantic/v1/decorator.py", line 40, in wrapper_function
    return vd.call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/<user>/workspace/playground/venv/lib/python3.11/site-packages/pydantic/v1/decorator.py", line 134, in call
    return self.execute(m)
           ^^^^^^^^^^^^^^^
  File "/home/<user>/workspace/playground/venv/lib/python3.11/site-packages/pydantic/v1/decorator.py", line 206, in execute
    return self.raw_function(**d, **var_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/<user>/workspace/playground/venv/lib/python3.11/site-packages/lakefs_sdk/api/repositories_api.py", line 153, in create_repository_with_http_info
    raise ApiTypeError(
lakefs_sdk.exceptions.ApiTypeError: Got an unexpected keyword argument 'read_only' to method create_repository
```
```


### Contact details

_No response_

**Comment by N-o-Z** [comment] 2024-08-29 18:18
@yonipeleg33 This is not a bug, it's a feature request. Do we have any compelling business reason to add it?

**Comment by yonipeleg33** [comment] 2024-08-29 20:54
@N-o-Z I was not aware of it being a feature request, and it sounds weird to me, TBH - if you don't want to use the `read_only` flag, just don't use it, what is the motivation behind requesting a feature to _remove_ an optional argument?

Anyway, I opened the bug because I wanted to use this flag and couldn't, and simply assumed it was a missing implementation, no business-y reason.

**Comment by N-o-Z** [comment] 2024-08-29 21:13
`read_only` is used mostly internally, I can't think of a user scenario where they'd want to create a read only repo.
You can change the title if you want, I think the discussion we had here also provide enough relevant context

**Comment by tkalir** [comment] 2024-10-14 18:17
Hi @N-o-Z,
Regarding the PR, I found this issue under "good first issue" and since the tag remained for a while I assumed that it should be implemented. Feel free to close the PR if you conclude that it is not needed. Thanks for reviewing

**Comment by N-o-Z** [comment] 2024-10-14 20:30
> Hi @N-o-Z, Regarding the PR, I found this issue under "good first issue" and since the tag remained for a while I assumed that it should be implemented. Feel free to close the PR if you conclude that it is not needed. Thanks for reviewing

Thanks @tkalir, sorry for the mix-up. I would be happy to suggest other good first issues if you still wish to contribute

**Comment by N-o-Z** [comment] 2024-10-14 20:53
Closing based on conversation here and in [PR](https://github.com/treeverse/lakeFS/pull/8280#pullrequestreview-2367193180).
At the moment I can't find any actual user use case for adding this parameter.

**Closed by N-o-Z** 2024-10-14 20:53 UTC
Labels: bug, good first issue
