### ISSUE TITLE
Align lakeFS clients publish

### ISSUE THREAD

**Issue by lynnro314** [treeverse/lakeFS#3863] opened 2022-08-08 12:35 UTC
As for now, we publish lakeFS hadoopFS client jar and uber-jar to Maven central, and publish the Spark client jar to Maven, but the Spark client uber-jar to a public S3 bucket.
Both clients should be published in the same manner: 
- Non-assembly vs assembly. 
- Maven central and/or s3.

**Comment by talSofer** [comment] 2022-10-02 14:31
duplicate of https://github.com/treeverse/lakeFS/issues/3766

**Closed by talSofer** 2022-10-02 14:31 UTC
Labels: team/ecosystem
