### ISSUE TITLE
Diff outputs objects for files with no changes (by copy)

### ISSUE THREAD

**Issue by xubofei1983** [treeverse/lakeFS#1840] opened 2021-04-30 21:37 UTC
Steps to reproduce:  
1. create a repo with a folder and some files in folder.  us aws s3 sync to local.
~/temp   aws s3  sync s3://test/master/folder folder                          
download: s3://test/master/folder/GCA_010094145.1 to folder/GCA_010094145.1
download: s3://test/master/folder/README.md to folder/README.md

~/temp   aws s3 sync folder s3://test/master/folder    (no files uploaded as expected.)

2. rename folder to folder_cp and copy same content back to folder. ( To simulate generation of the same data content.)
~/temp   mv folder folder_cp                                                       
~/temp   cp -r folder_cp folder 

3. try aws s3 sync, it now triggers reupload.
~/temp   aws s3 sync folder s3://test/master/folder                              
upload: folder/GCA_010094145.1 to s3://test/master/folder/GCA_010094145.1
upload: folder/README.md to s3://test/master/folder/README.md

4. try lakectl diff, it shows all files changed.
~/temp lakectl diff lakefs://test@master                                    
~ modified folder/GCA_010094145.1
~ modified folder/README.md 

Expected:  No files should be reuploaded.  No files in diff.
Actual: Files uploaded and diffs outputs all files.

**Comment by talSofer** [comment] 2021-05-02 14:18
Hi @xubofei1983, 
Regarding the concern that you raised about files being uploaded with `aws s3 sync`, this logic belongs to aws s3 and therefore we support it. We reproduced this in s3 as follows: 
```bash
test % aws s3 sync s3://bucket/folder folder         
download: s3://bucket/folder/test-file.txt to folder/test-file.txt    

test % mv folder folder_cp
test % ls 
folder_cp
test % cp -r folder_cp folder

ls -lsa folder
3 May  2 10:26 test-file.txt
test % ls -lsa folder_cp 
3 May  2 10:25 test-file.txt

test % aws s3 sync folder s3://bucket/folder 
upload: folder/test-file.txt to s3://bucket/folder/test-file.txt      
```

The second issue that you brought up (files are in diff) exposed inconsistency between uncommitted diff to committed diff (uncommitted diff = staging<>branch, committed diff = branch1<>branch2), https://github.com/treeverse/lakeFS/pull/1841 fixes it. With this pr, running `~/temp lakectl diff lakefs://test@master` will show no changes. 

Your issue opened up a general discussion on how to handle changes in `mtime`. https://github.com/treeverse/lakeFS/issues/1844 and https://github.com/treeverse/lakeFS/issues/1849 are the follow-up items. We will appreciate your thoughts.

**Closed** 2021-05-03 09:30 UTC
Labels: bug, next

**Comment by xubofei1983** [comment] 2021-05-04 16:16
@guy-har I have a following question with a particular use case:

1. We branch out from master.

2. We generate a new dataset with thousands files (say 1T but only few files changed content).  We upload them to lakes with sync as above.

3. we diff new branch with master, (I suppose will show no diffs with your fix?).  Then merge into master.

Now how many storage will lakeFS need from s3?   1T, 2T,  or 3T?

**Comment by xubofei1983** [comment] 2021-05-04 16:19
the related new feature is https://github.com/treeverse/lakeFS/issues/1765.

But we are interested to learn what the current behavior first.

Thanks,

**Comment by guy-har** [comment] 2021-05-04 16:33
@xubofei1983 
With the current implementation the answer would be 2T
Merging is a metadata action which does not add data.
Adding data that already exist will add the data to S3.
We will add very soon a garbage collection process, that will remove all data that isn't referenced by any commit (and then the answer would be 1T).

**Comment by xubofei1983** [comment] 2021-05-04 16:36
Thanks @guy-har,

I guess 1T means  we merge branch to master and then DELETE the old branch?   if old branch still remains (like a tag in git system),  it would be 2T then?

**Comment by guy-har** [comment] 2021-05-04 17:03
@xubofei1983 
No need to remove the branch, In your case the additional 1T wont be included in the changes, therefore it won't be included in the commit.
The garbage collection process will remove that data because it's not referenced from any commit.
