### ISSUE TITLE
Unclear error message when pointing to non-existing branch

### ISSUE THREAD

**Issue by itaiad200** [treeverse/lakeFS#1255] opened 2021-01-20 13:51 UTC
aws s3 cp --endpoint-url http://s3.lakefs-poc.wnwd-dev.com:8000 --profile lakeFS <local_path_to_file> s3://<bucket_name>/<non_existing_branch>/<path_to_file>
upload failed: .<local_path_to_file> to  s3://<bucket_name>/<non_existing_branch>/<path_to_file> An error occurred (NoSuchBucket) when calling the UploadPart operation: **The specified bucket does not exist**

Bucket does exist, it's the branch that isn't there.

**Comment by ozkatz** [comment] 2021-01-20 14:03
Duplicate of #1220

**Closed** 2021-01-20 14:06 UTC
Labels: area/gateway, bug, x/duplicate
