### ISSUE TITLE
Architecture overview page displays two load balancers when it should be a single one

### ISSUE THREAD

**Issue by Jonathan-Rosenberg** [treeverse/lakeFS#2858] opened 2022-01-04 14:54 UTC
In the architecture page, under the [`Overview` section](https://docs.lakefs.io/understand/architecture.html#overview), the overview image shows two LBs pointing to a lakeFS environment. This is no longer true and should show a single LB pointing to that environment.

**Comment by talSofer** [comment] 2022-02-21 14:54
Duplicate of #2958

**Closed by talSofer** 2022-02-21 14:54 UTC
Labels: good first issue, docs
