### ISSUE TITLE
Staging behaviour is unclear when uploading the exact same objects

### ISSUE THREAD

**Issue by itaiad200** [treeverse/lakeFS#3756] opened 2022-07-26 11:34 UTC
It is not allowed to commit to a branch with 0 changes to objects. However the term "empty staging area" is not clear when uploading the same objects again.
**Example**: lakeFS committed data with object `foo.bar`. No entries in the staging area. The same object `foo.bar` is uploaded under the same name. The list of uncommitted changes doesn't show the object and the UI commit button is disabled, which makes sense. However I was able to commit using `lakectl`. The commit diff view shows `no changes`.

This occurs in the DB (postgres) implementation of graveler, KV implementation isn't finished yet but will be able to resolve this.

**Comment by N-o-Z** [comment] 2022-07-26 13:47
Maybe the solution is during the upload object to check vs committed - and if they have the same Identity return an error?

**Comment by nopcoder** [comment] 2022-10-29 14:17
I've tested the above and I think we need to update as it is more as a non trivial bug.
We are able to update the last modified time and see no uncommitted data on a branch.
To reproduce:
1. Upload an object.
2. Commit changes.
3. Upload the same object again. The last update time on the UI/CLI was updated and changed is listed on the UI's "Uncommitted changes" or the CLI using 'diff'.

**Comment by nopcoder** [comment] 2022-12-15 14:00
Discussed the issue with @ozkatz - it seems that the current implementation is the one that would introduce less issues, as we do not include the timestamp as part of the checksum. Having the verify/check the checksum when we set the data will slow the main operation flow with another read access.
So for now keeping the staging stage and throwing the update after the commit is the accepted behaviour.

**Comment by arielshaqed** [comment] 2022-12-15 14:07
I completely agree with this existing behaviour, but...

Not sure why the GUI commit button should be disabled.  I mean, I understand why it happens the way it's implemented... I just don't understand why the GUI blocks something that I could legitimately do from the CLI or the API.

**Comment by nopcoder** [comment] 2022-12-15 15:05
@arielshaqed looking into it behaviour - think at this place we can have a better UX

**Comment by nopcoder** [comment] 2022-12-15 16:12
@arielshaqed right as always - the UI does the eq. to `lakectl diff lakefs://my-repo/main`.
This is the reason why the button is disabled.
The `lakectl commit` calls to commit directly which does the commit and in the above case assume that the entry found in stage override the entry in the base commit. The code assumed that you added the entry because you already checked the identity (which is not true in this case).
This is why the behaviour in the UI doesn't match.

**Closed** 2022-12-21 20:13 UTC
Labels: bug, team/versioning-engine
