### ISSUE TITLE
Lakctl ingest stages more objects than source S3 bucket

### ISSUE THREAD

**Issue by ccaloian** [treeverse/lakeFS#2983] opened 2022-02-28 08:25 UTC
When ingesting a dataset from an S3 bucket to LakeFS using `lakectl ingest`. The source bucket contains around 15k objects, however the command seems to be stuck staging objects recursively. I interrupted the command when more than 3M objects were staged.

I am reproducing below the command and the output. While I want to protect the name of the bucket, I am masking the real names below, while trying to preserve the structure of the paths, _i.e._ path parts with same letter have same name. I suspect this might be important while debugging since it looks like the staging gets stuck in a recursive call.

```
$ lakectl ingest --from s3://<A-B-C-D-E-F>/ --to lakefs://<A-B-C-D>/<D-E-F>/data/raw/                                                                                              
Staged 3021418 objects so far...
```

The storage namespace for the `<A-B-C-D>` LakeFS repository is `s3://<our-lakefs-storage>/data/<A-B-C-D>`.

See also the [Slack #help channel thread](https://lakefs.slack.com/archives/C016726JLJW/p1645531902045139).

**Comment by itai-david** [comment] 2022-03-08 23:44
Found the cause - a misuse of the s3 pagination causes infinte loop when more than 1000 (page size) objects exists in the ingested directory.
A fix is in place andf now I'm working on a test to prevent future such cases

**Closed** 2022-03-23 03:24 UTC
Labels: bug, contributor, team/versioning-engine
