### ISSUE TITLE
[Bug]: Repo created for Unity Delta Sharing doesn't show any data in the UI on the main branch

### ISSUE THREAD

**Issue by kesarwam** [treeverse/lakeFS#6568] opened 2023-09-08 18:59 UTC
### What happened?

Created a repo named "unity-demo" for Unity Delta Sharing. Objects tab in lakeFS UI shows error "No Data" on the main branch:
[unity-demo repo URL in lakeFS Cloud](https://treeverse.us-east-1.lakefscloud.io/repositories/unity-demo/objects)

![image](https://github.com/treeverse/lakeFS/assets/93291915/57769f51-4172-4d29-8590-78e4f124efbe)

Uploaded few objects to the main branch and committed changes. Still getting "No Data" error message on the main branch. But if I go to a particular commit then I can see the data:
![image](https://github.com/treeverse/lakeFS/assets/93291915/43158ec5-ada1-42ba-94cf-f1c770f1f1c0)

![image](https://github.com/treeverse/lakeFS/assets/93291915/3322fb16-0b20-4d25-9e9f-2854952e89b2)

This issue is happening with only this repo which is configured for the Unity Delta Sharing.

### lakeFS version

0.107.0

### How lakeFS is installed

lakeFS Cloud

### Contact details

amit.kesarwani@treeverse.io

**Comment by arielshaqed** [comment] 2023-09-11 09:27
@kesarwam This is _before_ trying to apply Delta Sharing, right?  Nothing here goes through the Delta Sharing server, so I am removing that from the title.  **Please** feel free to restore the original title if I am wrong!

**Comment by arielshaqed** [comment] 2023-09-11 09:34
Annoying... I just tried it and failed to reproduce it:
![screenshot of including URL bar of Objects tab in webui displaying repo unity-demo branch main](https://github.com/treeverse/lakeFS/assets/7802932/7825926a-25e5-4642-a0da-3b32d79e665e).

I'll have to close this as "unable to reproduce" if it's also stopped happening to you, so I'm reassigning it back for now.  Obviously this is not a satisfactory conclusion.  The next time it happens, could you:
* Go the the JavaScript Console (Ctrl+Shift+C), network tab and then record a reload of the page?
* Give even more details of the steps you took before reaching this stage?

THANKS!

**Comment by kesarwam** [comment] 2023-09-11 20:11
@arielshaqed I was still having the same issue. Then I checked JavaScript Console (Ctrl+Shift+C), network tab. I saw that it was getting "No Data" response from the disk cache. I cleared the cache and issue got resolved. I don't know why it was using cache for this.

**Closed** 2023-09-12 13:59 UTC
Labels: bug
