### ISSUE TITLE
Nessie is often timing-out in Spark tests

### ISSUE THREAD

**Issue by itaiad200** [treeverse/lakeFS#2883] opened 2022-01-23 10:12 UTC
We should either check what causing the flakiness or make the timeout longer. Examples:
https://github.com/treeverse/lakeFS/runs/4803247848
https://github.com/treeverse/lakeFS/runs/4801417391
https://github.com/treeverse/lakeFS/runs/4800661911

**Comment by idanovo** [comment] 2022-03-14 10:50
It looks like increasing the timeout is not the right solution. As you can see in the checks of [this](https://github.com/treeverse/lakeFS/pull/3037) PR,  Test lakeFS S3 with Spark 2.x thick client step usually takes only 4 minutes to finish. We need to put an effort in order to understand why it sometimes reaches its timeout which is 8 minutes.

**Comment by N-o-Z** [comment] 2022-04-04 12:45
Closing it as part of #3153
The timeout issue is inconsistent and can be related to many root causes (low resources on VM, connectivity issue etc.)
Hopefully reducing the spark client log verbosity could at least alleviate the symptom (potentially solving the issue).
Suggest to re-open if issue presists

**Comment by talSofer** [comment] 2022-04-05 10:14
Re-opening because the failure is back https://github.com/treeverse/lakeFS/runs/5820481573?check_suite_focus=true

**Comment by N-o-Z** [comment] 2022-04-06 08:48
☹️

**Closed** 2022-05-09 19:22 UTC
Labels: bug, area/system-tests, team/ecosystem
