### ISSUE TITLE
[Bug]: Importing on S3 returns Success but 0 objects imported

### ISSUE THREAD

**Issue by ozkatz** [treeverse/lakeFS#6282] opened 2023-07-30 15:00 UTC
### What happened?

Current Behavior:
What actually happened, including error codes if applies.
        
Steps to Reproduce:
1. in the lakeFS UI, click import
2. use a publicly accessible bucket (e.g. [common crawl, as hosted by AWS](https://aws.amazon.com/marketplace/pp/prodview-zxtb4t54iqjmy?sr=0-1&ref_=beagle&applicationId=AWSMPContessa)) - `s3://commoncrawl/` as the source
3. run import

### Expected Behavior

Expected Behavior:
clicking "import" should result in a commit that introduces many new objects.
Instead, the import finishes successfully but with 0 objects imported.

### lakeFS Version

0.104.0

### Deplyoment

AWS on lakeFS Cloud, AWS on local machine

### Affected Clients

UI (haven't tested other clients)

**Comment by N-o-Z** [comment] 2023-07-30 15:57
@ozkatz,
Running locally on master and v0.104.0 I could not reproduce the issue

**Comment by N-o-Z** [comment] 2023-07-31 08:55
Verified that the issue is the IAM role used in treeverse org which does not allow access to the public bucket.
Investigating the reason...

**Comment by itaiad200** [comment] 2023-07-31 14:38
Unable to reproduce it on my playground env https://treeverse-surroundin.us-east-1.lakefscloud.io/repositories

**Comment by N-o-Z** [comment] 2023-08-04 16:10
Fixed in: #6213
Thanks @guy-har !

**Closed by N-o-Z** 2023-08-04 16:10 UTC
Labels: bug
