### ISSUE TITLE
Docs: show minimal permissions required for working with pre-signed URLs.

### ISSUE THREAD

**Issue by ozkatz** [treeverse/lakeFS#6299] opened 2023-08-01 13:56 UTC
Currently the lakeFS docs show instructions on how to use lakeFS [with minimal IAM permissions](https://docs.lakefs.io/howto/deploy/aws.html#prepare-your-s3-bucket) on AWS.

With the introduction of pre-signed URLs that also work from the client, we can also add a pre-signed mode: allow the lakeFS IAM role to Put/Get objects, but only from specific IP addresses or VPCs.

More info: https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_condition-keys.html

Relevant keys:

* [aws:referer](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_condition-keys.html#condition-keys-referer)
* [aws:SourceVpc](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_condition-keys.html#condition-keys-sourcevpc)
* [aws:SourceIp](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_condition-keys.html#condition-keys-sourceip)

Perhaps there are more.

The definition of done should be a recommended IAM role that allows lakeFSFS to work with full functionality, and the CLI/UI with full functionality, without allowing a lakeFS instance on another AWS account (think lakeFS Cloud..) to access the data directly - but only to sign the URLs.

**Comment by Isan-Rivkin** [comment] 2023-08-22 11:51
Deferring the D.O.D here to add documentation because currently its impossible to completely achieve block from Get/Put for lakeFS. 
There are several bugs / features we need to figure out before doing that. 
- Create Repo: `dummy` file in the storage namespace root. 
- Commits / Merge needs access to  `_lakeFS`
- UI: Get /Download Object [bug](https://github.com/treeverse/lakeFS/issues/6393)
- UI: Markdown rendering [bug](https://github.com/treeverse/lakeFS/issues/6412) 
- UI: DuckDB doesn't work with pre-sign. 
- Import: Needs access to `_lakefs` directory.
- Sample Data when creating repository - will not work needs access to /data dir. 
- Actions: Needs access to /data dir to read the contents. 

Will prioritize the follow issues to achieve no get/post for lakeFS permissions. 

(CC: @itaiad200 )

**Comment by itaiad200** [comment] 2023-08-22 12:39
> * Create Repo: `dummy` file in the storage namespace root.

**Blocker**: users can't create repositories.

> * UI: Get /Download Object [bug](https://github.com/treeverse/lakeFS/issues/6393)

Fixed with https://github.com/treeverse/lakeFS/pull/6462?

> * UI: Markdown rendering [bug](https://github.com/treeverse/lakeFS/issues/6412)

Not a blocker but we should prioritize.

> * UI: DuckDB doesn't work with pre-sign.

Tough one, I don't think it's a blocker but I could be convinced otherwise.

> * Sample Data when creating repository - will not work needs access to /data dir.

**Blocker** - It's a UI thing, right? Can't we use presign for it?

> * Actions: Needs access to /data dir to read the contents.

**Blocker** - Ouch, that's a pain. We need a smart, resilient workaround for this.

@ozkatz do you concur?

**Comment by Isan-Rivkin** [comment] 2023-08-22 16:39
@itaiad200 

> Fixed with https://github.com/treeverse/lakeFS/pull/6462?

nope, that's not related. 

> Tough one, I don't think it's a blocker but I could be convinced otherwise

Agreed-  in terms of R.O.I. It seems to me that the root issue is that DuckDB does not support working with pre-sign URL's so its really one as you said., @ozkatz please correct me if Im wrong. 

> Blocker - It's a UI thing, right? Can't we use presign for it?

Nope, the feature is indeed a UI thing but,the root cause of it comes from `Actions: Needs access to /data dir to read the contents.`

And that's an issue indeed sure tight now we use streaming approach to get/put those objects and ignoring pre-sign. 
But, even if we use pre-sign lakeFS server will not be able to execute hooks before commits because the server itself is restricted by source `vpc / account ID / IP`  for get requests.

Everything else - 💯

**Comment by ozkatz** [comment] 2023-08-23 15:33
Thanks @Isan-Rivkin  - I think it's absolutely reasonable for specific features to not be available in pre-signed *only* mode.

I'd say that the immediate blocker is of course the ability to create repositories.
We'll document that duckDB in the UI + sample data are current limitations for pre-signed only mode.

**Closed** 2023-08-30 14:52 UTC
Labels: area/UI, docs, improvement, area/block-adapter, area/auth, contributor, area/client/hadoopfs, AWS
