### ISSUE TITLE
lakectl autocomplete nouns

### ISSUE THREAD

**Issue by nopcoder** [treeverse/lakeFS#654] opened 2020-09-25 16:08 UTC
Have the completions code complete our "nouns" when relevant.
Example:
```
lakectl fs upload --source <tab> // should suggest files
lakectl repo delete <tab> // should suggest repositories names
```

**Comment by kichloo** [comment] 2020-09-26 16:52
@nopcoder Though I am beginner in this, I can complete it with some help. So, I would like to take this issue.

**Comment by nopcoder** [comment] 2020-09-26 16:57
Sure, let me know if you have questions about the issue or the code.

**Comment by kichloo** [comment] 2020-09-27 04:20
Yes, kindly help me regarding it!

**Comment by nopcoder** [comment] 2020-09-30 08:09
@kichloo we are using Cobra, here you can find information about the current completion - https://github.com/spf13/cobra/blob/master/shell_completions.md
There you can also find information on how to add "Completion of nouns" to each command we mapped.
Our documentation https://docs.lakefs.io/reference/commands.html#commands-cli-reference holds the reference of all the command, but you can also find the same in the standard project structure based on Cobra.

**Comment by avats-dev** [comment] 2020-10-06 08:44
@kichloo are you still working on this one? Let me know, I want to try this one.

**Comment by johnnyaug** [comment] 2020-10-14 08:47
Hey @kichloo, still working on this?

**Comment by kichloo** [comment] 2020-10-14 09:32
The issue is now open!

**Comment by fumblehool** [comment] 2020-10-16 15:39
Hi, I can work on this if nobody is currently working on it.

**Comment by nopcoder** [comment] 2020-10-25 14:42
@fumblehool still interested?

**Comment by fumblehool** [comment] 2020-10-27 04:51
@nopcoder Unfortunately, I'm unable to work on it right now.

**Comment by whoAbhishekSah** [comment] 2021-01-26 17:54
Hello @nopcoder I would like to work on this issue. Can you assign it to me?

**Closed** 2022-10-09 12:59 UTC
Labels: good first issue, area/lakectl, hacktoberfest, team/versioning-engine
