### ISSUE TITLE
[Bug]: with High Level Python Wrapper: repository.branch returns success even if branch doesn't exist

### ISSUE THREAD

**Issue by kesarwam** [treeverse/lakeFS#7614] opened 2024-03-29 16:23 UTC
### What happened?

repository.branch returns success even if branch doesn't exist.
        
Steps to Reproduce:
1. import lakefs 
2. lakefs.Repository("test").branch("eaiugertuq38tjeer")
3.  lakefs.Repository("test").branch("eaiugertuq38tjeer").id

### Affected clients

python lakefs 0.4.1

### Contact details

amit.kesarwani@treeverse.io

**Comment by N-o-Z** [comment] 2024-03-31 08:34
@kesarwam This behavior is by design.
Objects in the HL SDK are lazily evaluated in order to avoid unnecessary calls to the server.
This is also similar to how boto3 and many other data packages work.
If you think this is something that needs to be changed - please open a feature request.
Closing for now

**Closed by N-o-Z** 2024-03-31 08:34 UTC
Labels: bug, contributor
