### ISSUE TITLE
lakeFSFS fail writing in DBR 12.0 (probably w/ Unity Catalog)

### ISSUE THREAD

**Issue by talSofer** [treeverse/lakeFS#4923] opened 2023-01-02 09:17 UTC
Trying to write a simple data frame into lakeFS throwing the following exception: 
```
java.io.IOException: get object metadata using underlying wrapped s3 client
Caused by: java.lang.NoSuchMethodException: com.databricks.sql.acl.fs.CredentialScopeFileSystem.getWrappedFs()
```

Runtime: 
* DBR 12.0
* io.lakefs:hadoop-lakefs-assembly:0.1.9 
* cluster config:
```
spark.hadoop.fs.s3a.impl shaded.databricks.org.apache.hadoop.fs.s3a.S3AFileSystem
spark.hadoop.fs.s3a.endpoint s3.eu-west-1.amazonaws.com
spark.hadoop.fs.lakefs.secret.key ...
spark.hadoop.fs.lakefs.access.key ...
spark.hadoop.fs.lakefs.endpoint http://...:8000/api/v1
spark.hadoop.fs.lakefs.impl io.lakefs.LakeFSFileSystem
```

Based on https://lakefs.slack.com/archives/C016726JLJW/p1672413801272199

**Comment by rinzool** [comment] 2023-01-02 10:57
I found something interesting:
With a _No Isolation shared_ cluster **it works**, but it doesn't work with a _Single User_ cluster
(Same spark config, same notebook)

**Comment by arielshaqed** [comment] 2023-01-02 12:45
> I found something interesting: With a _No Isolation shared_ cluster **it works**, but it doesn't work with a _Single User_ cluster (Same spark config, same notebook)

Thanks, I am able to reproduce with this, but **I get a _different_ error**:

> IOException: Failed to read job commit marker: LakeFSFileStatus{path=lakefs://understand-lakefs-repo/production/testing/ariels/1000/_committed_7972024009585360853; isDirectory=false; length=198; replication=0; blocksize=67108864; modification_time=1672654508000; access_time=0; owner=; group=; permission=rw-rw-rw-; isSymlink=false; hasAcl=false; isEncrypted=false; isErasureCoded=false}
> Caused by: AccessDeniedException: s3a://my-lakefs-managed-bucket/data/gqe5lblbvfqevbd2rtd0/cepatatbvfqevbd2rtg0: getFileStatus on s3a://my-lakefs-managed-bucket/data/gqe5lblbvfqevbd2rtd0/cepatatbvfqevbd2rtg0: com.amazonaws.services.s3.model.AmazonS3Exception: Forbidden; request: HEAD https://my-lakefs-managed-bucket.s3.us-east-1.amazonaws.com data/gqe5lblbvfqevbd2rtd0/cepatatbvfqevbd2rtg0 {} Hadoop 3.3.4, aws-sdk-java/1.12.189 Linux/5.4.0-1088-aws OpenJDK_64-Bit_Server_VM/25.345-b01 java/1.8.0_345 scala/2.12.14 vendor/Azul_Systems,_Inc. cfg/retry-mode/legacy com.amazonaws.services.s3.model.GetObjectMetadataRequest; Request ID: NJ2CYPEPR0MDN2Q5, Extended Request ID: zOwlRDFRjtWHkiNg8KNQ2EGBwZkIUyduW4i96P7+Jvbb/RX4Eh3M7vLlKfhjXygn5PCw4rt2O7U=, Cloud Provider: AWS, Instance ID: i-080166a4bdbda466c (Service: Amazon S3; Status Code: 403; Error Code: 403 Forbidden; Request ID: NJ2CYPEPR0MDN2Q5; S3 Extended Request ID: zOwlRDFRjtWHkiNg8KNQ2EGBwZkIUyduW4i96P7+Jvbb/RX4Eh3M7vLlKfhjXygn5PCw4rt2O7U=; Proxy: null), S3 Extended Request ID: zOwlRDFRjtWHkiNg8KNQ2EGBwZkIUyduW4i96P7+Jvbb/RX4Eh3M7vLlKfhjXygn5PCw4rt2O7U=:403 Forbidden
> Caused by: AmazonS3Exception: Forbidden; request: HEAD https://my-lakefs-managed-bucket.s3.us-east-1.amazonaws.com data/gqe5lblbvfqevbd2rtd0/cepatatbvfqevbd2rtg0 {} Hadoop 3.3.4, aws-sdk-java/1.12.189 Linux/5.4.0-1088-aws OpenJDK_64-Bit_Server_VM/25.345-b01 java/1.8.0_345 scala/2.12.14 vendor/Azul_Systems,_Inc. cfg/retry-mode/legacy com.amazonaws.services.s3.model.GetObjectMetadataRequest; Request ID: NJ2CYPEPR0MDN2Q5, Extended Request ID: zOwlRDFRjtWHkiNg8KNQ2EGBwZkIUyduW4i96P7+Jvbb/RX4Eh3M7vLlKfhjXygn5PCw4rt2O7U=, Cloud Provider: AWS, Instance ID: i-080166a4bdbda466c (Service: Amazon S3; Status Code: 403; Error Code: 403 Forbidden; Request ID: NJ2CYPEPR0MDN2Q5; S3 Extended Request ID: zOwlRDFRjtWHkiNg8KNQ2EGBwZkIUyduW4i96P7+Jvbb/RX4Eh3M7vLlKfhjXygn5PCw4rt2O7U=; Proxy: null)

**Comment by rinzool** [comment] 2023-01-02 13:04
> Thanks, I am able to reproduce with this, but I get a different error:
@arielshaqed Looks like your databricks cluster cannot access S3 bucket 
```Service: Amazon S3; Status Code: 403; Error Code: 403 Forbidden```

**Comment by arielshaqed** [comment] 2023-01-02 13:46
> > Thanks, I am able to reproduce with this, but I get a different error:
> 
> @arielshaqed It looks like your databricks cluster cannot access S3 bucket `Service: Amazon S3; Status Code: 403; Error Code: 403 Forbidden`

Yeah that was a silly configuration error while going through different possibilities.  I have this configuration:
```conf
spark.hadoop.fs.lakefs.impl io.lakefs.LakeFSFileSystem
spark.hadoop.fs.lakefs.secret.key shhhh
spark.hadoop.fs.s3a.access.key AKIAyeahyeah
spark.hadoop.fs.s3a.endpoint s3.us-east-1.amazonaws.com
spark.master local[*, 4]
spark.databricks.cluster.profile singleNode
spark.hadoop.fs.s3a.impl shaded.databricks.org.apache.hadoop.fs.s3a.S3AFileSystem
spark.hadoop.fs.s3a.secret.key shhh-shhh
spark.hadoop.fs.lakefs.access.key AKIAyeahwhatever
spark.hadoop.fs.lakefs.endpoint https://treeverse.us-east-1.lakefscloud.io/api/v1
spark.master local[*, 4]
spark.databricks.cluster.profile singleNode
spark.databricks.delta.multiClusterWrites.enabled true
```

The `spark.master` and `spark.databricks.cluster.profile` settings are those requested by DataBricks.  The `spark.databricks.delta.multiClusterWrites.enabled` setting is there just in case it matters -- but I tried setting it to `true`, to `false`, and omitting it entirely.

@rinzool, just to make sure: do you also have
```conf
spark.hadoop.fs.s3a.impl shaded.databricks.org.apache.hadoop.fs.s3a.S3AFileSystem
```
in your configuration?

**Comment by arielshaqed** [comment] 2023-01-04 12:33
## Updates 2023-01-04

1. I believe that the appearance of `CredentialScopeFileSystem` in error messages on this issue is related to using Unity Catalog.  This is also a difference between my working tested configuration and @rinzool's failing configuration.

   Unity Catalog (apparently) uses IAM roles, and the wording on this class name suggests it is a FileSystem wrapper.
1. Assuming that this is the case, I plan to fix by using CredentialScopeFileSystem.getUnderlyingFs to retrieve an "underlying" FS, similarly to how we currently call `getWrappedFs` on other FileSystems.  (We can perform this call using Java reflection).
1. Testing still requires a failing configuration, and we hope to gain access to Unity Catalog soon.

See also #4927 which proposes how to _refactor_ the client-fetching code so it better reports such errors in future and will be easier to extend.

**Comment by arielshaqed** [comment] 2023-05-08 10:11
Back on it!!1!

**Comment by arielshaqed** [comment] 2023-05-17 14:24
It currently seems unlikely that you can configure Unity to write to lakeFS.  So SQL queries (which are serverless) will not work, DataBricks will have to add a configuration knob to allow lakeFS to hook in.  Specifically you would need either to configure Unity to use a different S3 gateway, and point that at lakeFS; or be able to apply a full Hadoop configuration to Unity to cause it to accept "lakefs://..." URLs.  (Or of course get DataBricks to support lakefs://... URLs.)

I _was_ able to write on a Unity-enabled cluster, on S3.  DataBricks assume a role in this cluster, and now you need to allow _that role_ to write to your storage namespace.  Once that was in, everything worked nicely.

Above I ran with `singleNode`, which is obviously _not_ relevant for Unity.  That failure looks like a configuration error.

I am closing this as:
1. We do have a workaround for clusters, and
1. I have no way to advance on full Unity until DataBricks open the platform a bit.

## PLEASE REOPEN (or open a new issue)

If:
1. This is an insufficient answer; OR
1. You have additional requirements; OR
1. You work for DataBricks and can help lakeFS with this!

**Closed by arielshaqed** 2023-05-17 14:24 UTC
Labels: bug, team/ecosystem
