### ISSUE TITLE
Docs: revert branch command is wrong

### ISSUE THREAD

**Issue by itaiad200** [treeverse/lakeFS#2339] opened 2021-08-09 13:58 UTC
The docs [here](https://docs.lakefs.io/usecases/production.html) use the example code:
   `lakectl branch reset lakefs://example-repo/stream-1 --commit ~79RU9aUsQ9GLnU`
To “Roll back a branch to a previous commit using the CLI”, however reset appears to only undo uncommitted changes rather than roll back to old commits, which is currently revert. Also the `--commit` flag for reset doesn’t exist.

**Comment by johnnyaug** [comment] 2021-08-10 09:12
Duplicate of #1637 - suggest closing #1637 because it has an outdated link

**Closed** 2021-08-10 09:26 UTC
Labels: docs
