### ISSUE TITLE
Garbage Collection: Delete retention policy from the GUI

### ISSUE THREAD

**Issue by Jonathan-Rosenberg** [treeverse/lakeFS#3216] opened 2022-04-13 16:13 UTC
Currently there's no way to delete a retention policy from the GUI. 
We should allow it...

**Comment by talSofer** [comment] 2023-02-16 10:42
duplicate of #https://github.com/treeverse/lakeFS/issues/4142

**Closed by talSofer** 2023-02-16 10:42 UTC
Labels: team/ecosystem
