### ISSUE TITLE
[Bug]: Wrapping does not behave consistently on setup API keys screen

### ISSUE THREAD

**Issue by rmoff** [treeverse/lakeFS#5253] opened 2023-02-15 17:45 UTC
### What happened?

On the `You're all set` screen of lakeFS setup the wrapping of fields does not behave consistently. At a width that should enable full display of them the icon wraps and sits over the key text, until the width shrinks to a certain point and then it displays correctly. 

In action: ![](https://user-images.githubusercontent.com/3671582/219024951-58c981b7-7cca-4674-8597-c3a07b273d65.gif)

Specifics

* Looks good at 2244 ![CleanShot 2023-02-15 at 17 41 12](https://user-images.githubusercontent.com/3671582/219109709-6792e844-32f2-4100-b3df-8d3376a97681.png)
* Copy icon wraps unnecessarily and confusingly at 2172 ![CleanShot 2023-02-15 at 17 41 33](https://user-images.githubusercontent.com/3671582/219109850-dd3f2493-b013-40b1-be8f-23611d8369a2.png)
* Wrapping gets worse as the width shrinks. Here it is at 785. The icons obscure the text. ![CleanShot 2023-02-15 at 17 42 21](https://user-images.githubusercontent.com/3671582/219110094-23a39ed9-5865-4304-a28c-75d4efb24d95.png)
* At ~763 the wrapping fixes itself and the full width of the display is used so that things aren't overlapping and obscured  ![CleanShot 2023-02-15 at 17 43 15](https://user-images.githubusercontent.com/3671582/219110242-01500fce-9211-4db2-978a-900d26a9b6e0.png)

### Expected Behavior

The readability of the content should be prioritised and make full use of the screen display if necessary. 

### lakeFS Version

0.93

### Deplyoment

docker

### Affected Clients

n/a

### Relevant logs output

```shell
Chrome Version 110.0.5481.100 (Official Build) (arm64)
MacOS
```

### Contact Details

robin.moffatt@treeverse.io

**Comment by eladlachmi** [comment] 2023-02-15 18:03
Duplicate of #5217

**Closed** 2023-02-15 18:04 UTC
Labels: bug, area/UI, team/cloud-native
