### ISSUE TITLE
Document guarantees of Spark metadata client support for a Spark version

### ISSUE THREAD

**Issue by arielshaqed** [treeverse/lakeFS#3050] opened 2022-03-15 10:18 UTC
Discover, decide and document what we want to test to claim that the Spark
metadata client supports given Spark / Hadoop / Scala versions.

**Comment by talSofer** [comment] 2022-10-02 15:00
duplicate of https://github.com/treeverse/lakeFS/issues/2800

**Closed by talSofer** 2022-10-02 15:00 UTC
Labels: team/ecosystem
