### ISSUE TITLE
[Bug]: PostCommitHook is failed

### ISSUE THREAD

**Issue by zonghsh888** [treeverse/lakeFS#6276] opened 2023-07-29 02:26 UTC
### What happened?

Current Behavior:
The objects in the created tag aren't same with the objects in the ref branch when creating the tag. 
The log didn't show the commitID which didn't been found. 
Let's say the commitID is 222 in current action and the previous commitID is 111. And after the create tag action, the objects in the tag are same with the previous commit (111). It should be same with the commitID（222）。
By the way, this only happend once by now. The following step may not reproduce the error. It only show the steps of my logic.  
        
Steps to Reproduce:
1. Use S3 SDK to upload big file (about 10G)
2. use lakefs client to call stageObject method 
3. use lakefs client to call commit method
4. use lakefs client to call create tag method

### Expected Behavior

Expected Behavior:
the objects in created tag should be same with the objects in the current commit in stead of previous commit. 

### lakeFS Version

0.66

### Deplyoment

helm-cart

### Affected Clients

java lakefs client 

### Relevant logs output

```shell
"2023-07-19T15:24:112"level-info hog-"Filtering action"func="pkg/actions.(*Service).Run"file="build/pkg/actions/secvice.go:135#record="(20230719152411arS0z6I-post-commie 1-model-yhua-uploed s3://1-model 19 15:24:10.965646821 +0000 UTC -+3850437.923294485 (892a7dca97290an26a0cff1918e8630028038dcd00729c0d47900c7de230b6d7]ap[])70eff1ec25a0171835e0bb5d1612ef89f4001e416328101ffc846e6791b9e21 20230719152410cVyP sI-c)"spec="(post-commit main)
1-"2023-07-19T15:24:112"level=into message-"Async run of hook failed"func-"pkg/actions.("Service).asyncRun.func1"file-"build/pkg/actiona/service.go:118" error="list actions from commit: 1isting actions:commit not found (9-V1.4.0001)24ca2423b54454ccc57081e2538da3a12e9458bb879cc1e205e907ad72br70e2 2023-07-19 15:24:10.965646821 +0000 UTC -+3850437.923294485
```

### Contact Details

zonghsh007@126.com

**Comment by idanovo** [comment] 2023-07-30 14:03
Hi @zonghsh888

I couldn't reproduce the issue using latest lakeFS version (v0.104.0).
Can you please try to use a newer version of lakeFS client?

**Comment by idanovo** [comment] 2023-08-01 09:31
Hi @zonghsh888 

I close this issue for now as it non-reproducible.
Feel free to open it again in case you face this issue again.

**Closed by idanovo** 2023-08-01 09:31 UTC
Labels: bug, contributor
