### ISSUE TITLE
Improvements of big merges to an empty branch

### ISSUE THREAD

**Issue by itaiad200** [treeverse/lakeFS#1556] opened 2021-03-02 11:56 UTC
Scenario: empty master branch, import branch created from it. Many files committed to the import branch. When trying to merge them to master, Graveler will use the diff iterator and iterate on each entry and create everything from scratch.

Possible solution: Copy the ranges (where there are no overlaps between source and destination) from the source branch.

**Comment by ozkatz** [comment] 2021-03-04 09:24
duplicate of #1439

**Closed by ozkatz** 2021-03-04 09:24 UTC
