### ISSUE TITLE
Test, document and publish Spark clients support matrix

### ISSUE THREAD

**Issue by arielshaqed** [treeverse/lakeFS#3057] opened 2022-03-15 10:29 UTC
Dimensions (at least):

* lakeFSFS / metadata
* Spark
* Hadoop
* Scala (metadata client only)

**Comment by talSofer** [comment] 2022-10-02 14:03
duplicate of https://github.com/treeverse/lakeFS/issues/2800

**Closed by talSofer** 2022-10-02 14:03 UTC
Labels: team/ecosystem
