### ISSUE TITLE
Export job fails but ends with status 0

### ISSUE THREAD

**Issue by johnnyaug** [treeverse/lakeFS#2089] opened 2021-06-09 13:41 UTC
A customer ran an export job on Spark EMR. The S3 credentials were misconfigured.

Hence, the export job was unable to read data files from the `_lakefs` prefix in S3.
However, the job showed up as succesful on Spark.

Need to try to reproduce this issue.

Example command:
```bash
spark-submit --conf spark.hadoop.lakefs.api.url=https://lakefs.example.com/api/v1/ \
  --conf spark.hadoop.fs.s3a.access.key=<BAD-S3-CREDENTIALS> \
  --conf spark.hadoop.fs.s3a.secret.key=<BAD-S3-CREDENTIALS> \
  --conf spark.hadoop.lakefs.api.access_key=<LAKEFS_ACCESS_KEY> \
  --conf spark.hadoop.lakefs.api.secret_key=<LAKEFS_SECRET_KEY> \
  --jars http://treeverse-clients-us-east.s3-website-us-east-1.amazonaws.com/lakefs-spark-client-301/0.1.4-SNAPSHOT/lakefs-spark-client-301-assembly-0.1.4-SNAPSHOT.jar \
  --class io.treeverse.clients.Main export-app example-repo s3://example-bucket/exported-data/ \
  --branch=main
```

**Comment by itaiad200** [comment] 2021-06-15 14:59
Unable to reproduce both locally and on EMR. spark-submit throws exception and returns error code.
Might been fixed with the release of the new version.

Closing for now and will reopen if reoccur.

**Closed by itaiad200** 2021-06-15 14:59 UTC
Labels: area/client/spark, bug
