### ISSUE TITLE
Pyspark 'premature end of content' error with 0.1.4 lakeFS hadoop filesystem

### ISSUE THREAD

**Issue by itaiad200** [treeverse/lakeFS#2810] opened 2021-12-19 09:36 UTC
stacktrace:

answer = 'xro159'
gateway_client = <py4j.java_gateway.GatewayClient object at 0x113bd5c18>
target_id = 'o158', name = 'showString'

    def get_return_value(answer, gateway_client, target_id=None, name=None):
        """Converts an answer received from the Java gateway into a Python object.

        For example, string representation of integers are converted to Python
        integer, string representation of objects are converted to JavaObject
        instances, etc.

        :param answer: the string returned by the Java gateway
        :param gateway_client: the gateway client used to communicate with the Java
            Gateway. Only necessary if the answer is a reference (e.g., object,
            list, map)
        :param target_id: the name of the object from which the answer comes from
            (e.g., *object1* in `object1.hello()`). Optional.
        :param name: the name of the member from which the answer comes from
            (e.g., *hello* in `object1.hello()`). Optional.
        """
        if is_error(answer)[0]:
            if len(answer) > 1:
                type = answer[1]
                value = OUTPUT_CONVERTER[type](answer[2:], gateway_client)
                if answer[1] == REFERENCE_TYPE:
                    raise Py4JJavaError(
                        "An error occurred while calling {0}{1}{2}.\n".
>                       format(target_id, ".", name), value)
E                   py4j.protocol.Py4JJavaError: An error occurred while calling o158.showString.
E                   : org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 3.0 failed 1 times, most recent failure: Lost task 0.0 in stage 3.0 (TID 202, localhost, executor driver): org.apache.http.ConnectionClosedException: Premature end of Content-Length delimited message body (expected: 15069; received: 4219
E                   	at org.apache.http.impl.io.ContentLengthInputStream.read(ContentLengthInputStream.java:178)
E                   	at org.apache.http.impl.io.ContentLengthInputStream.read(ContentLengthInputStream.java:198)
E                   	at org.apache.http.impl.io.ContentLengthInputStream.close(ContentLengthInputStream.java:101)
E                   	at org.apache.http.conn.BasicManagedEntity.streamClosed(BasicManagedEntity.java:166)
E                   	at org.apache.http.conn.EofSensorInputStream.checkClose(EofSensorInputStream.java:228)
E                   	at org.apache.http.conn.EofSensorInputStream.close(EofSensorInputStream.java:172)
E                   	at java.io.FilterInputStream.close(FilterInputStream.java:181)
E                   	at java.io.FilterInputStream.close(FilterInputStream.java:181)
E                   	at java.io.FilterInputStream.close(FilterInputStream.java:181)
E                   	at java.io.FilterInputStream.close(FilterInputStream.java:181)
E                   	at com.amazonaws.services.s3.model.S3ObjectInputStream.abort(S3ObjectInputStream.java:90)
E                   	at org.apache.hadoop.fs.s3a.S3AInputStream.close(S3AInputStream.java:199)
E                   	at java.io.FilterInputStream.close(FilterInputStream.java:181)
E                   	at org.apache.parquet.io.DelegatingSeekableInputStream.close(DelegatingSeekableInputStream.java:50)
E                   	at org.apache.parquet.hadoop.ParquetFileReader.close(ParquetFileReader.java:910)
E                   	at org.apache.parquet.hadoop.InternalParquetRecordReader.close(InternalParquetRecordReader.java:147)
E                   	at org.apache.parquet.hadoop.ParquetRecordReader.close(ParquetRecordReader.java:97)
E                   	at org.apache.spark.sql.execution.datasources.RecordReaderIterator.close(RecordReaderIterator.scala:62)
E                   	at org.apache.spark.sql.execution.datasources.RecordReaderIterator.hasNext(RecordReaderIterator.scala:44)
E                   	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:409)
E                   	at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.hasNext(FileScanRDD.scala:101)
E                   	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
E                   	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
E                   	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$13$$anon$1.hasNext(WholeStageCodegenExec.scala:636)
E                   	at org.apache.spark.sql.execution.SparkPlan$$anonfun$2.apply(SparkPlan.scala:255)
E                   	at org.apache.spark.sql.execution.SparkPlan$$anonfun$2.apply(SparkPlan.scala:247)
E                   	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$24.apply(RDD.scala:858)
E                   	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$24.apply(RDD.scala:858)
E                   	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
E                   	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:346)
E                   	at org.apache.spark.rdd.RDD.iterator(RDD.scala:310)
E                   	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
E                   	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:346)
E                   	at org.apache.spark.rdd.RDD.iterator(RDD.scala:310)
E                   	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
E                   	at org.apache.spark.scheduler.Task.run(Task.scala:123)
E                   	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:408)
E                   	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
E                   	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414)
E                   	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
E                   	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
E                   	at java.lang.Thread.run(Thread.java:748)
E
E                   Driver stacktrace:
E                   	at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1925)
E                   	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1913)
E                   	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1912)
E                   	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
E                   	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
E                   	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1912)
E                   	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:948)
E                   	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:948)
E                   	at scala.Option.foreach(Option.scala:257)
E                   	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:948)
E                   	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:2146)
E                   	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2095)
E                   	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2084)
E                   	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
E                   	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:759)
E                   	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2061)
E                   	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2082)
E                   	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2101)
E                   	at org.apache.spark.sql.execution.SparkPlan.executeTake(SparkPlan.scala:365)
E                   	at org.apache.spark.sql.execution.CollectLimitExec.executeCollect(limit.scala:38)
E                   	at org.apache.spark.sql.Dataset.org$apache$spark$sql$Dataset$$collectFromPlan(Dataset.scala:3389)
E                   	at org.apache.spark.sql.Dataset$$anonfun$head$1.apply(Dataset.scala:2550)
E                   	at org.apache.spark.sql.Dataset$$anonfun$head$1.apply(Dataset.scala:2550)
E                   	at org.apache.spark.sql.Dataset$$anonfun$52.apply(Dataset.scala:3370)
E                   	at org.apache.spark.sql.execution.SQLExecution$$anonfun$withNewExecutionId$1.apply(SQLExecution.scala:80)
E                   	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:127)
E                   	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:75)
E                   	at org.apache.spark.sql.Dataset.org$apache$spark$sql$Dataset$$withAction(Dataset.scala:3369)
E                   	at org.apache.spark.sql.Dataset.head(Dataset.scala:2550)
E                   	at org.apache.spark.sql.Dataset.take(Dataset.scala:2764)
E                   	at org.apache.spark.sql.Dataset.getRows(Dataset.scala:254)
E                   	at org.apache.spark.sql.Dataset.showString(Dataset.scala:291)
E                   	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
E                   	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
E                   	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
E                   	at java.lang.reflect.Method.invoke(Method.java:498)
E                   	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
E                   	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
E                   	at py4j.Gateway.invoke(Gateway.java:282)
E                   	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
E                   	at py4j.commands.CallCommand.execute(CallCommand.java:79)
E                   	at py4j.GatewayConnection.run(GatewayConnection.java:238)
E                   	at java.lang.Thread.run(Thread.java:748)
E                   Caused by: org.apache.http.ConnectionClosedException: Premature end of Content-Length delimited message body (expected: 15069; received: 4219
E                   	at org.apache.http.impl.io.ContentLengthInputStream.read(ContentLengthInputStream.java:178)
E                   	at org.apache.http.impl.io.ContentLengthInputStream.read(ContentLengthInputStream.java:198)
E                   	at org.apache.http.impl.io.ContentLengthInputStream.close(ContentLengthInputStream.java:101)
E                   	at org.apache.http.conn.BasicManagedEntity.streamClosed(BasicManagedEntity.java:166)
E                   	at org.apache.http.conn.EofSensorInputStream.checkClose(EofSensorInputStream.java:228)
E                   	at org.apache.http.conn.EofSensorInputStream.close(EofSensorInputStream.java:172)
E                   	at java.io.FilterInputStream.close(FilterInputStream.java:181)
E                   	at java.io.FilterInputStream.close(FilterInputStream.java:181)
E                   	at java.io.FilterInputStream.close(FilterInputStream.java:181)
E                   	at java.io.FilterInputStream.close(FilterInputStream.java:181)
E                   	at com.amazonaws.services.s3.model.S3ObjectInputStream.abort(S3ObjectInputStream.java:90)
E                   	at org.apache.hadoop.fs.s3a.S3AInputStream.close(S3AInputStream.java:199)
E                   	at java.io.FilterInputStream.close(FilterInputStream.java:181)
E                   	at org.apache.parquet.io.DelegatingSeekableInputStream.close(DelegatingSeekableInputStream.java:50)
E                   	at org.apache.parquet.hadoop.ParquetFileReader.close(ParquetFileReader.java:910)
E                   	at org.apache.parquet.hadoop.InternalParquetRecordReader.close(InternalParquetRecordReader.java:147)
E                   	at org.apache.parquet.hadoop.ParquetRecordReader.close(ParquetRecordReader.java:97)
E                   	at org.apache.spark.sql.execution.datasources.RecordReaderIterator.close(RecordReaderIterator.scala:62)
E                   	at org.apache.spark.sql.execution.datasources.RecordReaderIterator.hasNext(RecordReaderIterator.scala:44)
E                   	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:409)
E                   	at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.hasNext(FileScanRDD.scala:101)
E                   	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
E                   	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
E                   	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$13$$anon$1.hasNext(WholeStageCodegenExec.scala:636)
E                   	at org.apache.spark.sql.execution.SparkPlan$$anonfun$2.apply(SparkPlan.scala:255)
E                   	at org.apache.spark.sql.execution.SparkPlan$$anonfun$2.apply(SparkPlan.scala:247)
E                   	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$24.apply(RDD.scala:858)
E                   	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$24.apply(RDD.scala:858)
E                   	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
E                   	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:346)
E                   	at org.apache.spark.rdd.RDD.iterator(RDD.scala:310)
E                   	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
E                   	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:346)
E                   	at org.apache.spark.rdd.RDD.iterator(RDD.scala:310)
E                   	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
E                   	at org.apache.spark.scheduler.Task.run(Task.scala:123)
E                   	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:408)
E                   	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
E                   	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414)
E                   	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
E                   	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
E                   	... 1 more

/Users/dima/.virtualenvs/ww-python-env/lib/python3.6/site-packages/py4j/protocol.py:328: Py4JJavaError

**Comment by itaiad200** [comment] 2021-12-19 15:29
Versions:

Hadoop 2.7.3
Spark 2.4.7
lakeFS v0.45.0
lakeFS Hadoop client 0.1.4 - bundled with lakeFS api 0.56.0 client version.

**Comment by arielshaqed** [comment] 2021-12-21 08:42
I can reproduce this in `spark-shell` with these same Hadoop + Spark + client versions, and latest lakeFS (0.57.1).

```scala
val p = new Path("lakefs://boo/main/data/Shakespeare_data.csv")
val in = fs.open(p)
in.readByte()
in.close()
```

gives this stacktrace:
```
org.apache.http.ConnectionClosedException: Premature end of Content-Length delimited message body (expected: 10188854; received: 1602
  at org.apache.http.impl.io.ContentLengthInputStream.read(ContentLengthInputStream.java:178)
  at org.apache.http.impl.io.ContentLengthInputStream.read(ContentLengthInputStream.java:198)
  at org.apache.http.impl.io.ContentLengthInputStream.close(ContentLengthInputStream.java:101)
  at org.apache.http.conn.BasicManagedEntity.streamClosed(BasicManagedEntity.java:166)
  at org.apache.http.conn.EofSensorInputStream.checkClose(EofSensorInputStream.java:228)
  at org.apache.http.conn.EofSensorInputStream.close(EofSensorInputStream.java:172)
  at java.base/java.io.FilterInputStream.close(FilterInputStream.java:180)
  at java.base/java.io.FilterInputStream.close(FilterInputStream.java:180)
  at java.base/java.io.FilterInputStream.close(FilterInputStream.java:180)
  at java.base/java.io.FilterInputStream.close(FilterInputStream.java:180)
  at com.amazonaws.services.s3.model.S3ObjectInputStream.abort(S3ObjectInputStream.java:90)
  at org.apache.hadoop.fs.s3a.S3AInputStream.close(S3AInputStream.java:199)
  at java.base/java.io.FilterInputStream.close(FilterInputStream.java:180)
  ... 49 elided
```

**Comment by arielshaqed** [comment] 2021-12-21 08:44
This explains the various (complex) occurrences we have been seeing: they all appear to happen during various reads of the initial segment of a file.  (No idea why the Hadoop test suite and the rest of our test codes manage not to hit this.)

**Comment by arielshaqed** [comment] 2021-12-21 10:10
It's an error in the _actual_ S3A version we end up using... as opposed to what we think we use :-(

```scala
val s = new Path("s3a://treeverse-ariels-test-us/data/Shakespeare.csv")
val fs3 = s.getFileSystem(sc.hadoopConfiguration)
val j = fs3.open(s, 16384)
j.readByte()
j.close()
```

This is (sort-of) _good_ news: if we work around the buggy S3A implementation, maybe we can fix it in our code.

**Comment by arielshaqed** [comment] 2021-12-22 12:18
This looks very much like a buggy implementation is in play in Hadoop 2.7.3 and/or Spark 2.4.7.   I don't need to say "lakefs" to get this stacktrace:

```
[ariels@fedora hadoopfs]$ ~/stuff/spark-2.4.7-bin-hadoop2.7/bin/spark-shell  `cat ~/.secrets/aws-ariels.conf`  --master=local --jars $HOME/stuff/hadoop-2.7.3-jars/hadoop-aws-2.7.3.jar,$HOME/stuff/hadoop-2.7.3-jars/hadoop-auth-2.7.3.jar,$HOME/stuff/hadoop-2.7.3-jars/hadoop-annotations-2.7.3.jar,$HOME/stuff/hadoop-2.7.3-jars/aws-java-sdk-1.7.4.jar
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.spark.unsafe.Platform (file:/home/ariels/stuff/spark-2.4.7-bin-hadoop2.7/jars/spark-unsafe_2.11-2.4.7.jar) to method java.nio.Bits.unaligned()
WARNING: Please consider reporting this to the maintainers of org.apache.spark.unsafe.Platform
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
21/12/22 14:11:32 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
Spark context Web UI available at http://fedora:4040
Spark context available as 'sc' (master = local, app id = local-1640175095887).
Spark session available as 'spark'.
Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /___/ .__/\_,_/_/ /_/\_\   version 2.4.7
      /_/
         
Using Scala version 2.11.12 (OpenJDK 64-Bit Server VM, Java 11.0.13)
Type in expressions to have them evaluated.
Type :help for more information.

scala> import org.apache.hadoop.fs.Path
import org.apache.hadoop.fs.Path

scala> val s = new Path("s3a://treeverse-ariels-test-us/data/Shakespeare.csv")
s: org.apache.hadoop.fs.Path = s3a://treeverse-ariels-test-us/data/Shakespeare.csv

scala> val fs3 = s.getFileSystem(sc.hadoopConfiguration)
fs3: org.apache.hadoop.fs.FileSystem = org.apache.hadoop.fs.s3a.S3AFileSystem@c79a727

scala> val j = fs3.open(s, 16384)
j: org.apache.hadoop.fs.FSDataInputStream = org.apache.hadoop.fs.FSDataInputStream@f53070c

scala> j.readByte()
res0: Byte = 34

scala> j.close()
org.apache.http.ConnectionClosedException: Premature end of Content-Length delimited message body (expected: 10188854; received: 1631
  at org.apache.http.impl.io.ContentLengthInputStream.read(ContentLengthInputStream.java:178)
  at org.apache.http.impl.io.ContentLengthInputStream.read(ContentLengthInputStream.java:198)
  at org.apache.http.impl.io.ContentLengthInputStream.close(ContentLengthInputStream.java:101)
  at org.apache.http.conn.BasicManagedEntity.streamClosed(BasicManagedEntity.java:166)
  at org.apache.http.conn.EofSensorInputStream.checkClose(EofSensorInputStream.java:228)
  at org.apache.http.conn.EofSensorInputStream.close(EofSensorInputStream.java:172)
  at java.base/java.io.FilterInputStream.close(FilterInputStream.java:180)
  at java.base/java.io.FilterInputStream.close(FilterInputStream.java:180)
  at java.base/java.io.FilterInputStream.close(FilterInputStream.java:180)
  at java.base/java.io.FilterInputStream.close(FilterInputStream.java:180)
  at com.amazonaws.services.s3.model.S3ObjectInputStream.abort(S3ObjectInputStream.java:90)
  at org.apache.hadoop.fs.s3a.S3AInputStream.close(S3AInputStream.java:199)
  at java.base/java.io.FilterInputStream.close(FilterInputStream.java:180)
  ... 49 elided
```

The file `aws-ariels.conf` contains
```
-c spark.hadoop.fs.s3a.access.key=AKIAnotreally
-c spark.hadoop.fs.s3a.secret.key=come/on...
```

And I explicitly load these JARs:
```shell
[ariels@fedora hadoopfs]$ md5sum /home/ariels/stuff/hadoop-2.7.3-jars/hadoop-aws-2.7.3.jar /home/ariels/stuff/hadoop-2.7.3-jars/hadoop-auth-2.7.3.jar /home/ariels/stuff/hadoop-2.7.3-jars/hadoop-annotations-2.7.3.jar /home/ariels/stuff/hadoop-2.7.3-jars/aws-java-sdk-1.7.4.jar
99c918d7cacc7b084bcf7813a6315edd  /home/ariels/stuff/hadoop-2.7.3-jars/hadoop-aws-2.7.3.jar
471760b62af31e3bfe4e6a73929868d7  /home/ariels/stuff/hadoop-2.7.3-jars/hadoop-auth-2.7.3.jar
04144ea13aa1d654c3f57894153baa05  /home/ariels/stuff/hadoop-2.7.3-jars/hadoop-annotations-2.7.3.jar
89b90a3716fea91703187b6d89e2934c  /home/ariels/stuff/hadoop-2.7.3-jars/aws-java-sdk-1.7.4.jar
```

**Comment by arielshaqed** [comment] 2021-12-22 12:30
Sounds a lot like https://issues.apache.org/jira/browse/HTTPCLIENT-2176.  Maintainers say to [_ignore_ this exception](https://issues.apache.org/jira/browse/HTTPCLIENT-2176?focusedCommentId=17413001&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-17413001) -- which we shall do.

**Comment by arielshaqed** [comment] 2023-07-09 08:14
> Sounds a lot like https://issues.apache.org/jira/browse/HTTPCLIENT-2176. Maintainers say to [_ignore_ this exception](https://issues.apache.org/jira/browse/HTTPCLIENT-2176?focusedCommentId=17413001&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-17413001) -- which we shall do.

This workaround is easier for the _user_ to perform than for us.  Closing as:
1. It's not a bug in lakeFSFS.
1. There is a Spark workaround.
1. This issue is hard to reproduce and has not been reported in a long while.

**PLEASE** reopen if it happens to you -- and the more information you can give for reproducing, the better!

**Closed by arielshaqed** 2023-07-09 08:14 UTC
Labels: bug, contributor, team/ecosystem
